<?php
/**
 * Digitify portfolio — clients & projects registry
 *
 * Naming: folders Webdesign / Marketing / Media → project_type + img in assets/images/projects/
 *
 * @package Digitify
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Raw client portfolio (one client → multiple projects possible).
 *
 * @return array<int, array<string, mixed>>
 */
function digitify_get_portfolio_clients() {
	$clients = array(
		array(
			'key'      => 'the-pilav-truck',
			'name'     => 'The Pilav Truck',
			'location' => 'België',
			'projects' => array(
				array(
					'slug'         => 'the-pilav-truck',
					'type'         => 'website',
					'tag'          => 'Webdesign',
					'title'        => 'Website The Pilav Truck',
					'img'          => 'projects/project-the-pilav-truck-website.png',
					'featured'     => true,
					'year'         => '2025',
					'view_label'   => 'Bekijk website',
					'subtitle'     => 'Food brand website met sterke visuele identiteit',
					'intro'        => 'The Pilav Truck brengt Turkse pilav en streetfood naar de straat. Wij bouwden een website die smaak, energie en merkidentiteit vertaalt naar een online ervaring die honger opwekt en reserveringen stimuleert.',
					'services'     => array( 'UX/UI design', 'Responsive webdesign', 'Conversie-optimalisatie', 'SEO-basis' ),
					'challenge'    => 'Sterk offline concept, maar geen professionele site die locaties, menu en contact helder communiceert.',
					'approach'     => 'Onepage-structuur met foodfotografie, duidelijke CTA\'s en mobiel-first design voor social traffic.',
					'result'       => 'Levendige website die vertrouwen opbouwt en bezoekers naar contact of reservatie leidt.',
					'deliverables' => array( 'Custom webdesign', 'Responsive ontwikkeling', 'Locatie-overzicht', 'Performance-optimalisatie' ),
					'ton'          => 'Website',
					'lift'         => 'België',
					'elec'         => 'Live',
				),
			),
		),
		array(
			'key'      => 'next-hire',
			'name'     => 'Next Hire',
			'location' => 'België',
			'projects' => array(
				array(
					'slug'         => 'next-hire',
					'type'         => 'platform',
					'tag'          => 'Webdesign',
					'title'        => 'Platform Next Hire',
					'img'          => 'projects/project-next-hire-website.png',
					'featured'     => true,
					'year'         => '2025',
					'view_label'   => 'Bekijk platform',
					'subtitle'     => 'Recruitment platform met focus op conversie',
					'intro'        => 'Next Hire verbindt werkgevers en talent sneller. Een strakke, professionele website legt het platform helder uit en genereert kwalitatieve demo-aanvragen.',
					'services'     => array( 'Webdesign', 'UX/UI', 'Leadgeneratie', 'Responsive development' ),
					'challenge'    => 'Complexe diensten eenvoudig uitleggen en werkgevers overtuigen om contact op te nemen.',
					'approach'     => 'Heldere architectuur, trust-elementen en conversieformulieren op strategische plekken.',
					'result'       => 'Professionele positionering en meer gekwalificeerde leads.',
					'deliverables' => array( 'Multipage website', 'Conversie-elementen', 'Mobiel geoptimaliseerd', 'SEO-structuur' ),
					'ton'          => 'Platform',
					'lift'         => 'België',
					'elec'         => 'Live',
				),
			),
		),
		array(
			'key'      => 'breadless',
			'name'     => 'Breadless',
			'location' => 'België',
			'projects' => array(
				array(
					'slug'         => 'breadless',
					'type'         => 'website',
					'tag'          => 'Webdesign',
					'title'        => 'Website Breadless',
					'img'          => 'projects/project-breadless-website.png',
					'featured'     => true,
					'year'         => '2025',
					'view_label'   => 'Bekijk website',
					'subtitle'     => 'Premium food brand website',
					'intro'        => 'Breadless presenteert een uniek foodconcept zonder brood. De website weerspiegelt de premium uitstraling van het merk en neemt bezoekers mee in het verhaal.',
					'services'     => array( 'Brand webdesign', 'Storytelling', 'Responsive design', 'Contentstructuur' ),
					'challenge'    => 'Online even premium aanvoelen als het fysieke product.',
					'approach'     => 'Minimalistisch design, grote visuals en typografie als merkelement.',
					'result'       => 'Elegante site die het merk versterkt en conversie ondersteunt.',
					'deliverables' => array( 'Custom design', 'Productpresentatie', 'Contactintegratie', 'Snelle laadtijden' ),
					'ton'          => 'Website',
					'lift'         => 'België',
					'elec'         => 'Live',
				),
			),
		),
		array(
			'key'      => 'zon-dak',
			'name'     => 'Zon & Dak',
			'location' => 'België',
			'projects' => array(
				array(
					'slug'         => 'zon-dak',
					'type'         => 'advertentie',
					'tag'          => 'Marketing',
					'title'        => 'Advertentiecampagnes Zon & Dak',
					'img'          => 'projects/project-zon-dak-ad-1.png',
					'gallery'      => array( 'projects/project-zon-dak-ad-1.png', 'projects/project-zon-dak-ad-2.png', 'projects/project-zon-dak-ad-3.png', 'projects/project-zon-dak-ad.gif' ),
					'featured'     => true,
					'year'         => '2025',
					'view_label'   => 'Bekijk campagnes',
					'subtitle'     => 'Employer branding & leadgeneratie',
					'intro'        => 'Voor Zon & Dak zetten we Meta- en Google Ads in met creatieve content op maat — voor klanten én talentwerving in een krappe arbeidsmarkt.',
					'services'     => array( 'Meta Ads', 'Google Ads', 'Employer branding', 'Creative design' ),
					'challenge'    => 'Leads voor dakwerken én gekwalificeerde sollicitanten tegelijk genereren.',
					'approach'     => 'Gescheiden campagnes, A/B-testing en continue optimalisatie op cost-per-lead.',
					'result'       => 'Meetbare stijging in leads en sollicitaties met transparante rapportage.',
					'deliverables' => array( 'Advertentiecampagnes', 'Creative assets', 'Landing pages', 'Maandrapportage' ),
					'ton'          => 'Advertentie',
					'lift'         => 'Meta',
					'elec'         => 'Google',
				),
				array(
					'slug'         => 'zon-dak-media',
					'type'         => 'video',
					'tag'          => 'Media',
					'title'        => 'Videocontent Zon & Dak',
					'img'          => 'projects/project-zon-dak-media.png',
					'featured'     => false,
					'year'         => '2025',
					'view_label'   => 'Bekijk video',
					'subtitle'     => 'Employer branding video',
					'intro'        => 'Professionele videocontent die het vakmanschap en teamgevoel van Zon & Dak authentiek in beeld brengt — inzetbaar op social en in campagnes.',
					'services'     => array( 'Videoproductie', 'Employer branding', 'Social exports', 'Montage' ),
					'challenge'    => 'Vertrouwen en menselijkheid tonen in een competitieve sector.',
					'approach'     => 'Documentaire stijl, echte teamsfeer en platform-specifieke formats.',
					'result'       => 'Content die engagement verhoogt en employer branding versterkt.',
					'deliverables' => array( 'Brand video', 'Social clips', 'Employer content', 'Post-productie' ),
					'ton'          => 'Video',
					'lift'         => 'Video',
					'elec'         => 'Brand',
				),
			),
		),
		array(
			'key'          => 'duca-cleaning',
			'name'         => 'Duca Cleaning',
			'location'     => 'België',
			'website_url'  => 'https://ducacleaning.be/',
			'projects' => array(
				array(
					'slug'         => 'duca-cleaning',
					'type'         => 'advertentie',
					'tag'          => 'Marketing',
					'title'        => 'Advertenties Duca Cleaning',
					'img'          => 'projects/project-duca-cleaning-ad.png',
					'featured'     => true,
					'year'         => '2025',
					'view_label'   => 'Bekijk campagnes',
					'subtitle'     => 'Performance marketing schoonmaak',
					'intro'        => 'Gerichte Google- en Meta-campagnes die diensten helder communiceren en offerteaanvragen stimuleren met efficiënt budgetgebruik.',
					'services'     => array( 'Google Ads', 'Meta Ads', 'Ad creatives', 'Conversie-optimalisatie' ),
					'challenge'    => 'Maximale offertes in een prijsgevoelige markt.',
					'approach'     => 'Lokale targeting, vertrouwenwekkende copy en snelle landingspagina\'s.',
					'result'       => 'Lagere cost-per-lead en meer kwalitatieve aanvragen.',
					'deliverables' => array( 'Search campagnes', 'Display ads', 'Ad copy', 'Rapportage' ),
					'ton'          => 'Advertentie',
					'lift'         => 'Google',
					'elec'         => 'Meta',
				),
				array(
					'slug'         => 'duca-cleaning-media',
					'type'         => 'video',
					'tag'          => 'Media',
					'title'        => 'Video Duca Cleaning',
					'img'          => 'projects/project-duca-cleaning-media.png',
					'featured'     => false,
					'year'         => '2025',
					'view_label'   => 'Bekijk video',
					'subtitle'     => 'Merkbewustzijn via video',
					'intro'        => 'Professionele video die de diensten en betrouwbaarheid van Duca Cleaning visueel ondersteunt voor web en social.',
					'services'     => array( 'Videoproductie', 'Storytelling', 'Social clips' ),
					'challenge'    => 'Vertrouwen opbouwen in een competitieve schoonmaakmarkt.',
					'approach'     => 'Before/after storytelling en heldere service-uitleg in korte formats.',
					'result'       => 'Sterkere merkherkenning en hogere engagement.',
					'deliverables' => array( 'Brand video', 'Social snippets', 'Post-productie' ),
					'ton'          => 'Video',
					'lift'         => 'Video',
					'elec'         => 'Brand',
				),
			),
		),
		array(
			'key'      => 'amr-group',
			'name'     => 'AMR Group',
			'location' => 'België',
			'projects' => array(
				array(
					'slug'         => 'amr-group',
					'type'         => 'website',
					'tag'          => 'Webdesign',
					'title'        => 'Website AMR Group',
					'img'          => 'projects/project-amr-group-website.png',
					'featured'     => false,
					'year'         => '2024',
					'view_label'   => 'Bekijk website',
					'subtitle'     => 'Corporate group website',
					'intro'        => 'Professionele groepswebsite die meerdere entiteiten en diensten overzichtelijk presenteert onder één corporate dak.',
					'services'     => array( 'Corporate webdesign', 'Multipage', 'B2B structuur' ),
					'challenge'    => 'Meerdere merken coherent presenteren.',
					'approach'     => 'Heldere navigatie en aparte secties per entiteit.',
					'result'       => 'Coherente groepswebsite die vertrouwen uitstraalt.',
					'deliverables' => array( 'Corporate website', 'Entiteiten-overzicht', 'Contact' ),
					'ton'          => 'Website',
					'lift'         => 'België',
					'elec'         => 'Live',
				),
				array(
					'slug'         => 'amr-group-media',
					'type'         => 'video',
					'tag'          => 'Media',
					'title'        => 'Video AMR Group',
					'img'          => 'projects/project-amr-group-media.png',
					'featured'     => false,
					'year'         => '2024',
					'view_label'   => 'Bekijk video',
					'subtitle'     => 'Corporate merkvideo',
					'intro'        => 'Visuele content die de schaal, expertise en mensen achter AMR Group professioneel in beeld brengt.',
					'services'     => array( 'Videoproductie', 'Corporate storytelling', 'Post-productie' ),
					'challenge'    => 'Complex corporate verhaal compact en krachtig vertellen.',
					'approach'     => 'Interview-based storytelling met cinematische beelden.',
					'result'       => 'Video die vertrouwen opbouwt bij B2B-beslissers.',
					'deliverables' => array( 'Corporate video', 'Social exports', 'Montage' ),
					'ton'          => 'Video',
					'lift'         => 'Video',
					'elec'         => 'Brand',
				),
			),
		),
		array(
			'key'      => 'black-mountain',
			'name'     => 'Black Mountain',
			'location' => 'België',
			'projects' => array(
				array(
					'slug'         => 'black-mountain',
					'type'         => 'video',
					'tag'          => 'Media',
					'title'        => 'Brand content Black Mountain',
					'img'          => 'projects/project-black-mountain-media.png',
					'featured'     => true,
					'year'         => '2025',
					'view_label'   => 'Bekijk video',
					'subtitle'     => 'Visuele content & brand storytelling',
					'intro'        => 'Professionele visuele content die het merkverhaal krachtig vertelt — van concept tot exports voor web en social.',
					'services'     => array( 'Videoproductie', 'Fotografie', 'Post-productie', 'Social exports' ),
					'challenge'    => 'Authentieke beelden die emotie opwekken op alle kanalen.',
					'approach'     => 'Creatief concept, professionele opnames en platform-specifieke exports.',
					'result'       => 'Content die het merk versterkt en engagement verhoogt.',
					'deliverables' => array( 'Brand video', 'Fotografie', 'Social clips', 'Color grading' ),
					'ton'          => 'Video',
					'lift'         => 'Video',
					'elec'         => 'Brand',
				),
			),
		),
		array(
			'key'      => 'van-marcke',
			'name'     => 'Van Marcke',
			'location' => 'België',
			'projects' => array(
				array(
					'slug'         => 'van-marcke',
					'type'         => 'documentaire',
					'tag'          => 'Media',
					'title'        => 'Documentaire Van Marcke',
					'img'          => 'projects/project-sculture-x-van-marcke-media.png',
					'featured'     => false,
					'year'         => '2024',
					'view_label'   => 'Bekijk video',
					'subtitle'     => 'Documentaire & merkvideo',
					'intro'        => 'Documentaire en merkvideo in samenwerking met Sculture — authentiek vakmanschap en merkverhaal in beeld.',
					'services'     => array( 'Documentaire', 'Videoproductie', 'Storytelling', 'Post-productie' ),
					'challenge'    => 'Complex merkverhaal emotioneel vertalen.',
					'approach'     => 'Interview-based storytelling met cinematische montage.',
					'result'       => 'Krachtige merkvideo die vertrouwen opbouwt.',
					'deliverables' => array( 'Documentaire', 'Merkvideo', 'Social snippets', 'Color grading' ),
					'ton'          => 'Documentaire',
					'lift'         => 'Video',
					'elec'         => 'Brand',
				),
			),
		),
		array(
			'key'      => 'maximogusto',
			'name'     => 'Maximogusto',
			'location' => 'België',
			'projects' => array(
				array(
					'slug'       => 'maximogusto',
					'type'       => 'advertentie',
					'tag'        => 'Marketing',
					'title'      => 'Advertenties Maximogusto',
					'img'        => 'projects/project-maximogusto-ad.png',
					'gallery'    => array( 'projects/project-maximogusto-ad.png', 'projects/project-maximogusto-media.png' ),
					'featured'   => false,
					'year'       => '2024',
					'view_label' => 'Bekijk campagnes',
					'subtitle'   => 'Food marketing campagnes op Meta & Google',
					'intro'      => 'Maximogusto wilde meer zichtbaarheid en conversies in een competitieve food-markt. Wij bouwden performance campagnes met appetijtelijke creatives, strakke targeting en continue optimalisatie op cost-per-result.',
					'services'   => array( 'Meta Ads', 'Google Ads', 'Food marketing', 'Creative design', 'A/B-testing', 'Rapportage' ),
					'challenge'  => 'Het merk moest opvallen tussen talloze food-aanbieders, zonder budget te verspillen aan brede targeting. Creatives moesten honger opwekken én direct tot actie aanzetten.',
					'approach'   => 'We combineerden food-fotografie met seizoenscampagnes, splitsten prospecting en retargeting, en testten hooks, formats en doelgroepen wekelijks op basis van data.',
					'result'     => 'Meetbaar meer engagement, lagere cost-per-click en een stabielere stroom aan conversies — met transparante maandrapportages voor het team van Maximogusto.',
					'deliverables' => array( 'Meta & Google campagnes', 'Food creatives & copy', 'Doelgroepsegmentatie', 'Conversion tracking', 'Maandrapportage' ),
					'ton'        => 'Advertentie',
					'lift'       => 'Meta',
					'elec'       => 'Google',
				),
				array(
					'slug'       => 'maximogusto-media',
					'type'       => 'video',
					'tag'        => 'Media',
					'title'      => 'Video Maximogusto',
					'img'        => 'projects/project-maximogusto-media.png',
					'gallery'    => array( 'projects/project-maximogusto-media.png', 'projects/project-maximogusto-ad.png' ),
					'featured'   => false,
					'year'       => '2024',
					'view_label' => 'Bekijk video',
					'subtitle'   => 'Food content productie voor social & web',
					'intro'      => 'Naast campagnes produceerden we videocontent die de kwaliteit en smaak van Maximogusto tastbaar maakt — klaar voor social, ads en website.',
					'services'   => array( 'Videoproductie', 'Food styling', 'Social exports', 'Montage', 'Color grading' ),
					'challenge'  => 'Smaak, textuur en merkgevoel overbrengen in korte formats die scrollend publiek vasthouden.',
					'approach'   => 'Close-ups, motion en korte social clips afgestemd op Meta placements — afgestemd op de look van de advertentiecampagnes.',
					'result'     => 'Herkenbare food content die engagement verhoogt en naadloos aansluit bij de marketingfunnel.',
					'deliverables' => array( 'Brand video', 'Social clips', 'Ad-ready exports', 'Post-productie' ),
					'ton'        => 'Video',
					'lift'       => 'Video',
					'elec'       => 'Brand',
				),
			),
		),
		array(
			'key'      => 'picmemoments',
			'name'     => 'PicMeMoments',
			'location' => 'België',
			'projects' => array(
				array(
					'slug'       => 'picmemoments',
					'type'       => 'advertentie',
					'tag'        => 'Marketing',
					'title'      => 'Advertenties PicMeMoments',
					'img'        => 'projects/project-picmemoments-ad.png',
					'featured'   => false,
					'year'       => '2025',
					'view_label' => 'Bekijk campagnes',
					'subtitle'   => 'Social advertentiecampagnes',
					'intro'      => 'Gerichte Meta-campagnes met creatives op maat om PicMeMoments onder de aandacht te brengen.',
					'services'   => array( 'Meta Ads', 'Creative design', 'Targeting' ),
					'challenge'  => 'Bereik en conversie met beperkt budget.',
					'approach'   => 'Visuele hooks en doelgroepsegmentatie.',
					'result'     => 'Meer bereik en website-traffic.',
					'deliverables' => array( 'Social ads', 'Creative assets', 'Rapportage' ),
					'ton'        => 'Advertentie',
					'lift'       => 'Meta',
					'elec'       => 'Social',
				),
				array(
					'slug'       => 'picmemoments-media',
					'type'       => 'video',
					'tag'        => 'Media',
					'title'      => 'Video PicMeMoments',
					'img'        => 'projects/project-picmemoments-media.png',
					'featured'   => false,
					'year'       => '2025',
					'view_label' => 'Bekijk video',
					'subtitle'   => 'Event & moment content',
					'intro'      => 'Professionele video die de sfeer en service van PicMeMoments vastlegt voor marketing en social.',
					'services'   => array( 'Videoproductie', 'Event coverage', 'Social exports' ),
					'challenge'  => 'Emotie en spontaneiteit professioneel vastleggen.',
					'approach'   => 'Documentaire stijl met dynamische montage.',
					'result'     => 'Content die boekingen en engagement stimuleert.',
					'deliverables' => array( 'Promo video', 'Social clips', 'Montage' ),
					'ton'        => 'Video',
					'lift'       => 'Video',
					'elec'       => 'Brand',
				),
			),
		),
		array(
			'key'      => 'digitify',
			'name'     => 'Digitify',
			'location' => 'Gent',
			'projects' => array(
				array(
					'slug'         => 'digitify',
					'type'         => 'website',
					'tag'          => 'Webdesign',
					'title'        => 'Website Digitify',
					'img'          => 'projects/project-digitify-website.png',
					'featured'     => false,
					'year'         => '2025',
					'view_url'     => 'https://digitify.be',
					'view_label'   => 'Bekijk website',
					'subtitle'     => 'Practice what we preach',
					'intro'        => 'Onze eigen merkwebsite — premium design, cases en diensten die ons vakmanschap tonen.',
					'services'     => array( 'Brand webdesign', 'Case portfolio', 'SEO', 'Performance' ),
					'challenge'    => 'Creatief niveau en resultaatgerichte aanpak in één ervaring.',
					'approach'     => 'Premium layout, sterke typografie en snelle performance.',
					'result'       => 'Website die vertrouwen wekt bij prospects.',
					'deliverables' => array( 'Agency website', 'Case portfolio', 'Diensten', 'Contact' ),
					'ton'          => 'Website',
					'lift'         => 'Gent',
					'elec'         => 'Live',
				),
				array(
					'slug'         => 'leads-digitify',
					'type'         => 'webapp',
					'tag'          => 'Webdesign',
					'title'        => 'Leads webapp Digitify',
					'img'          => 'projects/project-leads-digitify-webapp.png',
					'featured'     => false,
					'year'         => '2025',
					'view_label'   => 'Bekijk webapp',
					'subtitle'     => 'Intern lead management platform',
					'intro'        => 'Interne webapp voor efficiënt leadbeheer — praktisch bewijs van onze development-capabilities.',
					'services'     => array( 'Webapp development', 'Dashboard design', 'UX/UI' ),
					'challenge'    => 'Leads overzichtelijk beheren met snelle acties.',
					'approach'     => 'Functioneel dashboard met focus op overzicht.',
					'result'       => 'Efficiëntere opvolging van prospects.',
					'deliverables' => array( 'Webapp', 'Dashboard', 'Lead tracking' ),
					'ton'          => 'Webapp',
					'lift'         => 'Intern',
					'elec'         => 'Live',
				),
			),
		),
	);

	// Single-project webdesign clients (batch).
	$web_clients = array(
		array( 'key' => 'akdeniz-restaurant', 'name' => 'Akdeniz Restaurant Gent', 'slug' => 'akdeniz-restaurant', 'img' => 'project-akdeniz-website.png', 'ton' => 'Website', 'lift' => 'Gent', 'subtitle' => 'Restaurantwebsite met reserveringsfocus' ),
		array( 'key' => 'blissful-body', 'name' => 'Blissful Body Gent', 'slug' => 'blissful-body', 'img' => 'project-blissful-body-website.png', 'ton' => 'Website', 'lift' => 'Gent', 'subtitle' => 'Wellness website met boekingsfocus' ),
		array( 'key' => 'im-the-label', 'name' => 'IM The Label', 'slug' => 'im-the-label', 'img' => 'project-im-the-label-webshop.png', 'ton' => 'Webshop', 'lift' => 'België', 'subtitle' => 'Fashion webshop met merkidentiteit', 'type' => 'webshop' ),
		array( 'key' => 'viridis-energy', 'name' => 'Viridis Energy', 'slug' => 'viridis-energy', 'img' => 'project-viridis-energy-website.png', 'ton' => 'Website', 'lift' => 'België', 'subtitle' => 'Corporate website energie & duurzaamheid' ),
		array( 'key' => 'cleanvisionpro', 'name' => 'CleanVisionPro', 'slug' => 'cleanvisionpro', 'img' => 'project-cleanvisionpro-website.png', 'ton' => 'Website', 'lift' => 'België', 'subtitle' => 'Service website met conversiefocus' ),
		array( 'key' => 'duricom', 'name' => 'Duricom', 'slug' => 'duricom', 'img' => 'project-duricom-website.png', 'ton' => 'Website', 'lift' => 'België', 'subtitle' => 'B2B website met dienstenfocus' ),
		array( 'key' => 'dwk-construct', 'name' => 'DWK Construct', 'slug' => 'dwk-construct', 'img' => 'project-dwk-construct-website.png', 'ton' => 'Website', 'lift' => 'België', 'subtitle' => 'Bouw & constructie website' ),
		array( 'key' => 'dakofferte', 'name' => 'Dakofferte', 'slug' => 'dakofferte', 'img' => 'project-dakofferte-website.png', 'ton' => 'Leadgen', 'lift' => 'België', 'subtitle' => 'Leadgeneratie website dakwerken', 'type' => 'leadgen' ),
		array( 'key' => 'giga-production', 'name' => 'GIGA Production', 'slug' => 'giga-production', 'img' => 'project-giga-production-website.png', 'ton' => 'Website', 'lift' => 'België', 'subtitle' => 'Productiebedrijf website' ),
		array( 'key' => 'hk-tech-projects', 'name' => 'HK Tech Projects', 'slug' => 'hk-tech-projects', 'img' => 'project-hk-tech-projects-website.png', 'ton' => 'Website', 'lift' => 'België', 'subtitle' => 'Tech & engineering website' ),
		array( 'key' => 'm-log', 'name' => 'M-Log', 'slug' => 'm-log', 'img' => 'project-m-log-website.png', 'ton' => 'Website', 'lift' => 'België', 'subtitle' => 'Logistiek & transport website' ),
		array( 'key' => 'properploeg', 'name' => 'Properploeg', 'slug' => 'properploeg', 'img' => 'project-properploeg-website.png', 'ton' => 'Website', 'lift' => 'België', 'subtitle' => 'Service website met merkidentiteit' ),
		array( 'key' => 'sonox', 'name' => 'SonoX', 'slug' => 'sonox', 'img' => 'project-sonox-website.png', 'ton' => 'Website', 'lift' => 'België', 'subtitle' => 'Compacte merkwebsite' ),
		array( 'key' => 'aison-kamaz', 'name' => 'Aison Kamaz', 'slug' => 'aison-kamaz', 'img' => 'project-aison-kamaz-website.png', 'ton' => 'Website', 'lift' => 'België', 'subtitle' => 'Automotive & transport website' ),
	);

	foreach ( $web_clients as $w ) {
		$type = isset( $w['type'] ) ? $w['type'] : 'website';
		$clients[] = array(
			'key'      => $w['key'],
			'name'     => $w['name'],
			'location' => $w['lift'],
			'projects' => array(
				array(
					'slug'         => $w['slug'],
					'type'         => $type,
					'tag'          => 'Webdesign',
					'title'        => $w['ton'] . ' ' . $w['name'],
					'img'          => 'projects/' . $w['img'],
					'featured'     => false,
					'year'         => '2024',
					'view_label'   => 'webshop' === $type ? 'Bekijk webshop' : ( 'leadgen' === $type ? 'Bekijk platform' : 'Bekijk website' ),
					'subtitle'     => $w['subtitle'],
					'intro'        => 'Digitify ontwikkelde een professionele online aanwezigheid voor ' . $w['name'] . ' — op maat van merk, doelgroep en conversiedoelen.',
					'services'     => array( 'Webdesign', 'Responsive development', 'UX/UI', 'SEO-basis' ),
					'challenge'    => 'Een online ervaring die vertrouwen wekt en bezoekers naar actie leidt.',
					'approach'     => 'Strategisch design, heldere structuur en performance-first development.',
					'result'       => 'Professionele website die het merk versterkt en resultaat oplevert.',
					'deliverables' => array( 'Custom design', 'Responsive site', 'Contact & conversie', 'SEO-basis' ),
					'ton'          => $w['ton'],
					'lift'         => $w['lift'],
					'elec'         => 'Live',
				),
			),
		);
	}

	// Marketing singles.
	$marketing_singles = array(
		array( 'key' => 'rifood', 'name' => 'RiFood', 'slug' => 'rifood', 'img' => 'project-rifood-ad.png', 'subtitle' => 'Social media advertentiecampagnes' ),
		array( 'key' => 'nam-construction', 'name' => 'NAM Construction', 'slug' => 'nam-construction', 'img' => 'project-nam-construction-ad.png', 'subtitle' => 'Performance advertentiecampagnes', 'year' => '2025' ),
	);
	foreach ( $marketing_singles as $m ) {
		$clients[] = array(
			'key'      => $m['key'],
			'name'     => $m['name'],
			'location' => 'België',
			'projects' => array(
				array(
					'slug'         => $m['slug'],
					'type'         => 'advertentie',
					'tag'          => 'Marketing',
					'title'        => 'Advertenties ' . $m['name'],
					'img'          => 'projects/' . $m['img'],
					'featured'     => false,
					'year'         => isset( $m['year'] ) ? $m['year'] : '2024',
					'view_label'   => 'Bekijk campagnes',
					'subtitle'     => $m['subtitle'],
					'intro'        => 'Gerichte advertentiecampagnes voor ' . $m['name'] . ' met creatives en targeting op maat.',
					'services'     => array( 'Meta Ads', 'Creative design', 'Campagnebeheer' ),
					'challenge'    => 'Maximaal bereik en conversie binnen budget.',
					'approach'     => 'Visuele creatives, A/B-testing en continue optimalisatie.',
					'result'       => 'Meer zichtbaarheid en meetbare resultaten.',
					'deliverables' => array( 'Advertentiecampagnes', 'Creatives', 'Rapportage' ),
					'ton'          => 'Advertentie',
					'lift'         => 'Meta',
					'elec'         => 'Social',
				),
			),
		);
	}

	// Media singles.
	$media_singles = array(
		array( 'besiktas', 'Besiktas', 'project-besiktas-media.png', 'Sport & event video' ),
		array( 'de-faam', 'De Faam', 'project-de-faam-media.png', 'Merkbewustzijn video' ),
		array( 'de-wittetandencenter', 'De Wittetandencenter', 'project-de-wittetandencenter-media.png', 'Praktijk video content' ),
		array( 'gvs-coaching', 'GVS Coaching', 'project-gvs-coaching-media.png', 'Coaching brand video' ),
		array( 'marydamme', "M'Arydamme", 'project-marydamme-media.png', 'Event & brand content' ),
		array( 'qrrefund', 'QRRefund', 'project-qrrefund-media.png', 'Product uitleg video' ),
		array( 'the-zone-izegem', 'The Zone Izegem', 'project-the-zone-izegem-media.png', 'Fitness & lifestyle video' ),
		array( 'turbofish', 'Turbofish', 'project-turbofish-media.png', 'Brand storytelling video' ),
	);
	foreach ( $media_singles as $row ) {
		list( $key, $name, $img, $subtitle ) = $row;
		$clients[] = array(
			'key'      => $key,
			'name'     => $name,
			'location' => 'België',
			'projects' => array(
				array(
					'slug'         => $key,
					'type'         => 'video',
					'tag'          => 'Media',
					'title'        => 'Video ' . $name,
					'img'          => 'projects/' . $img,
					'featured'     => false,
					'year'         => '2024',
					'view_label'   => 'Bekijk video',
					'subtitle'     => $subtitle,
					'intro'        => 'Professionele videoproductie voor ' . $name . ' — storytelling, montage en exports voor web en social.',
					'services'     => array( 'Videoproductie', 'Montage', 'Social exports', 'Color grading' ),
					'challenge'    => 'Merk en boodschap authentiek in beeld brengen.',
					'approach'     => 'Creatief concept, professionele opnames en platform-specifieke deliverables.',
					'result'       => 'Content die engagement en merkherkenning versterkt.',
					'deliverables' => array( 'Brand video', 'Social clips', 'Post-productie' ),
					'ton'          => 'Video',
					'lift'         => 'Video',
					'elec'         => 'Brand',
				),
			),
		);
	}

	return $clients;
}

/**
 * YouTube links from Video Digitify.pdf — keyed by project slug.
 *
 * @return array<string, string>
 */
/**
 * Known client websites — keyed by client key.
 *
 * @return array<string, string>
 */
function digitify_get_client_website_urls() {
	return array(
		'the-pilav-truck' => 'https://www.the-pilav-truck.be/',
		'breadless'       => 'https://breadless.be/',
		'duca-cleaning'   => 'https://ducacleaning.be/',
		'blissful-body'   => 'https://blissful-body.com/',
		'im-the-label'    => 'https://im-the-label.com/',
		'viridis-energy'  => 'https://viridis-energy.com/',
		'cleanvisionpro'  => 'https://cleanvisionpro.be/',
		'duricom'         => 'https://duricom.be/',
		'dwk-construct'   => 'https://dwk-construct.be/',
		'dakofferte'      => 'https://dakofferte.be/',
		'm-log'           => 'https://m-log.com/',
		'properploeg'     => 'https://properploeg.be/',
		'black-mountain'  => 'https://black-mountain.com/',
		'maximogusto'     => 'https://maximogusto.be/',
		'picmemoments'    => 'https://www.picmemoments.be/',
		'digitify'        => 'https://digitify.be/',
	);
}

function digitify_get_case_video_urls() {
	return array(
		'marydamme'             => 'https://www.youtube.com/watch?v=rNzJOK5f7KQ',
		'duca-cleaning-media'   => 'https://www.youtube.com/watch?v=X6zQQbCHjUg',
		'zon-dak-media'         => 'https://www.youtube.com/watch?v=qabOzhFpdyI',
		'black-mountain'        => 'https://www.youtube.com/watch?v=3MLWENY3DiU',
		'van-marcke'            => 'https://www.youtube.com/watch?v=iDNshO6X06s',
		'qrrefund'              => 'https://www.youtube.com/watch?v=8JSv4X3TCn4',
		'turbofish'             => 'https://www.youtube.com/watch?v=PRFF54c4n0k',
		'maximogusto-media'     => 'https://www.youtube.com/watch?v=_RRVn-d73NQ',
		'de-wittetandencenter'  => 'https://www.youtube.com/watch?v=lkB1CDfm-ok',
		'the-pilav-truck'       => 'https://www.youtube.com/watch?v=VFx5vbnTs3U',
		'the-zone-izegem'       => 'https://www.youtube.com/watch?v=AMZ1HPIx6Ks',
		'akdeniz-restaurant'    => 'https://www.youtube.com/watch?v=EqEscfk5qNI',
	);
}
